// variable name relationship to Google Font's Material Symbols
// https://fonts.google.com/icons?selected=Material+Icons&icon.set=Material+Symbols

export const Icons: { [key: string]: string } = {
  dashboard: 'grid_view',
  favorite: 'favorite',
  vault: 'account_balance',
  nft: 'filter_frames',
  initiative: 'diversity_1',
  gettingstarted: 'rocket_launch',
  propose: 'lightbulb_circle',
  docs: 'local_library',
  build: 'handyman',
  management: 'engineering',
  dao: 'handshake',
  govparam: 'settings',
  yfdswap: 'swap_horizontal_circle',
  swap: 'swap_horiz',
  softwaredev: 'computer',
  code: 'code',
  charity: 'volunteer_activism',
  escrow: 'savings',
  business: 'storefront',
  error: 'bug_report',
  praise: 'celebration',
  feedback: 'chat',
  vote: 'how_to_vote',
  proposal: 'lightbulb_circle',
  guardian: 'local_police',
  bid: 'waving_hand',
  task_complete: 'task_alt',
  deliverable_complete: 'assignment_turned_in',
  reputation: 'military_tech',
  compensation: 'savings',
  learn: 'psychology_alt',
  direction: 'explore',
  approve: 'recommend',
  judge: 'gavel',
  disbursement_approval: 'price_check',
  profit_share: 'share',
  research: 'biotech',
  team: 'groups'
};
